<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MemberCategoryHistorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('member_category_histories')->insert([
            [
                'summary_ym' => '202307',
                'member_id' => 1,
                'category_id' => 1,
                'category_name' => '拠出',
                'income_flg' => 1,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 1,
                'category_id' => 2,
                'category_name' => '食料・日用品',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 1,
                'category_id' => 3,
                'category_name' => '外食',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 1,
                'category_id' => 4,
                'category_name' => '臨時出費',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 2,
                'category_id' => 1,
                'category_name' => '拠出',
                'income_flg' => 1,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 2,
                'category_id' => 2,
                'category_name' => '食料・日用品',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 2,
                'category_id' => 3,
                'category_name' => '外食',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 2,
                'category_id' => 4,
                'category_name' => '臨時出費',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 1,
                'category_name' => '拠出',
                'income_flg' => 1,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 2,
                'category_name' => '食料・日用品',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 3,
                'category_name' => '外食',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 4,
                'category_name' => '臨時出費',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 5,
                'category_name' => '住宅ローン',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 6,
                'category_name' => '水道',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 7,
                'category_name' => '電気・ガス',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202307',
                'member_id' => 3,
                'category_id' => 8,
                'category_name' => 'インターネット・テレビ',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 1,
                'category_id' => 1,
                'category_name' => '拠出',
                'income_flg' => 1,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 1,
                'category_id' => 2,
                'category_name' => '食料・日用品',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 1,
                'category_id' => 3,
                'category_name' => '外食',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 1,
                'category_id' => 4,
                'category_name' => '臨時出費',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 2,
                'category_id' => 1,
                'category_name' => '拠出',
                'income_flg' => 1,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 2,
                'category_id' => 2,
                'category_name' => '食料・日用品',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 2,
                'category_id' => 3,
                'category_name' => '外食',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 2,
                'category_id' => 4,
                'category_name' => '臨時出費',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 1,
                'category_name' => '拠出',
                'income_flg' => 1,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 2,
                'category_name' => '食料・日用品',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 3,
                'category_name' => '外食',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 4,
                'category_name' => '臨時出費',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 5,
                'category_name' => '住宅ローン',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 6,
                'category_name' => '水道',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 7,
                'category_name' => '電気・ガス',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => '202308',
                'member_id' => 3,
                'category_id' => 8,
                'category_name' => 'インターネット・テレビ',
                'income_flg' => 0,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
        ]);
    }
}
