<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('payments')->insert([
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 1,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-01',
                'amount' => 200000,
                'payment_label' => '拠出',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-10',
                'amount' => 8068,
                'payment_label' => 'スーパー1',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 2,
                'payment_date' => '2023-07-10',
                'amount' => -3980,
                'payment_label' => 'ビール(家計から除外)',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 3,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-25',
                'amount' => 2706,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 1,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-01',
                'amount' => 100000,
                'payment_label' => '拠出',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 2,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-10',
                'amount' => 3135,
                'payment_label' => 'スーパー2',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 3,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-17',
                'amount' => 1975,
                'payment_label' => 'ケーキ',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 2,
                'categorized_payment_id' => 1,
                'payment_date' => null,
                'amount' => 451,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 2,
                'categorized_payment_id' => 2,
                'payment_date' => '2023-07-11',
                'amount' => 1287,
                'payment_label' => 'ホームセンター',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 3,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-18',
                'amount' => 4000,
                'payment_label' => 'ピザ',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 4,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-07-23',
                'amount' => 51872,
                'payment_label' => 'テーブル',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 5,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-25',
                'amount' => 132203,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 6,
                'categorized_payment_id' => 1,
                'payment_date' => null,
                'amount' => 4024,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 7,
                'categorized_payment_id' => 1,
                'payment_date' => null,
                'amount' => 7883,
                'payment_label' => '電気ガス',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 7,
                'categorized_payment_id' => 2,
                'payment_date' => null,
                'amount' => 27892,
                'payment_label' => '太陽光設備ローン',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202307,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 8,
                'categorized_payment_id' => 2,
                'payment_date' => null,
                'amount' => 3780,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 1,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-01',
                'amount' => 200000,
                'payment_label' => '拠出',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-02',
                'amount' => 7587,
                'payment_label' => 'スーパー1',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 2,
                'payment_date' => '2023-08-02',
                'amount' => -3980,
                'payment_label' => 'ビール(家計から除外)',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 3,
                'payment_date' => '2023-08-10',
                'amount' => 961,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 4,
                'payment_date' => null,
                'amount' => 3032,
                'payment_label' => 'ホームセンター',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 5,
                'payment_date' => '2023-08-15',
                'amount' => 8410,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 2,
                'categorized_payment_id' => 6,
                'payment_date' => '2023-08-15',
                'amount' => -3980,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 3,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-13',
                'amount' => 4763,
                'payment_label' => '寿司',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 1,
                'category_id' => 3,
                'categorized_payment_id' => 2,
                'payment_date' => '2023-08-15',
                'amount' => 2240,
                'payment_label' => 'ファミレス',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 1,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-01',
                'amount' => 100000,
                'payment_label' => '拠出',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 2,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-04',
                'amount' => 660,
                'payment_label' => 'スーパー2',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 2,
                'categorized_payment_id' => 2,
                'payment_date' => null,
                'amount' => 3330,
                'payment_label' => 'スーパー3',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 2,
                'categorized_payment_id' => 3,
                'payment_date' => '2023-08-22',
                'amount' => 2127,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 2,
                'category_id' => 4,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-15',
                'amount' => 4158,
                'payment_label' => 'お土産',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 2,
                'categorized_payment_id' => 1,
                'payment_date' => null,
                'amount' => 1450,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 2,
                'categorized_payment_id' => 2,
                'payment_date' => '2023-08-09',
                'amount' => 3363,
                'payment_label' => 'スーパー4',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 2,
                'categorized_payment_id' => 3,
                'payment_date' => null,
                'amount' => 3715,
                'payment_label' => 'スーパー1',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 3,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-13',
                'amount' => 6130,
                'payment_label' => '旅行先レストラン',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 3,
                'categorized_payment_id' => 2,
                'payment_date' => null,
                'amount' => 10780,
                'payment_label' => '宴会',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 4,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-16',
                'amount' => 5500,
                'payment_label' => '土産',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 5,
                'categorized_payment_id' => 1,
                'payment_date' => '2023-08-25',
                'amount' => 132203,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 7,
                'categorized_payment_id' => 1,
                'payment_date' => null,
                'amount' => 7378,
                'payment_label' => '電気ガス',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 7,
                'categorized_payment_id' => 2,
                'payment_date' => null,
                'amount' => 27892,
                'payment_label' => '太陽光設備ローン',
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'summary_ym' => 202308,
                'group_id' => 1,
                'member_id' => 3,
                'category_id' => 8,
                'categorized_payment_id' => 2,
                'payment_date' => null,
                'amount' => 3780,
                'payment_label' => null,
                'del_flg' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
        ]);
    }
}
